import sys
import logging
import os
from typing import List, Optional
from datetime import datetime
import httpx

from .schemas import TestCreate, TestResponse

""""
1. User fills form in CreateTest.tsx
2. Frontend makes HTTP POST to → http://backend:8000/api/v1/tests
3. Backend (FastAPI) receives request
4. Backend calls → nocoDB API (http://nocodb:8080/api/v1/db/data/...)
5. NocoDB writes to → PostgreSQL quality_tests table
6. PostgreSQL stores data permanently
7. Response flows back to frontend

https://community.nocodb.com/t/docker-compose-postgres-nocodb/1697/4
"""
logger = logging.getLogger("backend_tests_service")


class TestsService:
    """Service for managing tests using nocoDB API"""
    
    def __init__(self):
        self.nocodb_url = os.getenv("NOCODB_URL", "http://nocodb:8080")
        self.nocodb_token = os.getenv("NOCODB_API_TOKEN")
        self.table_id = os.getenv("NOCODB_TABLE_ID")  
        
        if not self.nocodb_token:
            logger.warning("NOCODB_API_TOKEN not set. Tests API will not work.")
        if not self.table_id:
            logger.warning("NOCODB_TABLE_ID not set. Tests API will not work.")
    
    def _get_headers(self):
        """Get headers for nocoDB API requests"""
        return {
            "xc-token": self.nocodb_token,
            "Content-Type": "application/json"
        }
    
    def _get_table_url(self):
        """Get the nocoDB table API URL"""
        if not self.table_id:
            raise ValueError("NOCODB_TABLE_ID not configured")
        return f"{self.nocodb_url}/api/v2/tables/{self.table_id}/records"
    
    async def create_test(self, test_data: TestCreate) -> TestResponse:
        """Create a new test via nocoDB API"""
        async with httpx.AsyncClient() as client:
            # Map to NocoDB column names (lowercase with underscores)
            payload = {
                "product_id": test_data.productId,
                "test_type": test_data.testType,
                "requester": test_data.requester,
                "assigned_to": test_data.assignedTo,
                "status": test_data.status,
                "deadline_at": test_data.deadlineAt.isoformat() if test_data.deadlineAt else None,
                # created_at and updated_at are auto-generated by NocoDB
            }
            
            # Remove None values (NocoDB may reject null for non-nullable fields)
            payload = {k: v for k, v in payload.items() if v is not None}
            
            logger.info(f"Sending payload to NocoDB: {payload}")
            
            response = await client.post(
                self._get_table_url(),
                headers=self._get_headers(),
                json=payload
            )
            logger.info(f"NocoDB response status: {response.status_code}")
            logger.info(f"NocoDB response body: {response.text}")
            
            response.raise_for_status()
            result = response.json()
            
            # Parse the response and return as TestResponse
            return TestResponse(**result)
    
    async def get_test(self, test_id: int) -> Optional[TestResponse]:
        """Get a test by ID via nocoDB API"""
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"{self._get_table_url()}/{test_id}",
                headers=self._get_headers()
            )
            if response.status_code == 404:
                return None
            response.raise_for_status()
            return TestResponse(**response.json())
    
    async def get_all_tests(self, skip: int = 0, limit: int = 100) -> List[TestResponse]:
        """Get all tests with pagination via nocoDB API"""
        async with httpx.AsyncClient() as client:
            response = await client.get(
                self._get_table_url(),
                headers=self._get_headers(),
                params={"offset": skip, "limit": limit}
            )
            response.raise_for_status()
            data = response.json()
            return [TestResponse(**item) for item in data.get("list", [])]
    
    async def update_test(self, test_id: int, test_data: dict) -> TestResponse:
        """Update a test via nocoDB API"""
        async with httpx.AsyncClient() as client:
            response = await client.patch(
                f"{self._get_table_url()}/{test_id}",
                headers=self._get_headers(),
                json=test_data
            )
            response.raise_for_status()
            return TestResponse(**response.json())
    
    async def delete_test(self, test_id: int) -> bool:
        """Delete a test via nocoDB API"""
        async with httpx.AsyncClient() as client:
            response = await client.delete(
                f"{self._get_table_url()}/{test_id}",
                headers=self._get_headers()
            )
            response.raise_for_status()
            return True


tests_service = TestsService()